Repository 100-hours-a-week/21-iceT-fe, pull requests merged in 2025-05, with the labels that each got.

#13 [FEATURE] 문제 해설 페이지 UI 개발
  koco/src/components/layout/PageHeader/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
  koco/src/pages/ProblemSolutionPage/index.tsx
  koco/src/routes/RootRoutes.tsx
  koco/src/styles/global.css
  koco/src/styles/index.css
  koco/src/temp/mock/solution.json
Labels: ✨feature, FE

#17 [FEATURE] 메인 페이지 - 레이더 차트 개발 (#14)
  koco/package-lock.json
  koco/package.json
  koco/src/pages/MainPage/components/ContinuousCard/index.tsx
  koco/src/pages/MainPage/components/ProfileCard/index.tsx
  koco/src/pages/MainPage/components/TotalStudyCard/components/RadarChart/index.tsx
  koco/src/pages/MainPage/components/TotalStudyCard/index.tsx
  koco/src/pages/MainPage/index.tsx
  koco/src/pages/ProblemListPage/index.tsx
  koco/src/temp/mock/dashboard.json
Labels: ✨feature, FE

#20 [CHORE] Axios 인스턴스 및 React-query 세팅 (#15)
  koco/package-lock.json
  koco/package.json
  koco/src/@types/api.ts
  koco/src/@types/problem/index.ts
  koco/src/@types/user/index.ts
  koco/src/App.tsx
  koco/src/apis/authApi.ts
  koco/src/apis/axios/index.ts
  koco/src/apis/problemApi.ts
  koco/src/apis/userApi.ts
  koco/src/hooks/custom/useFileInput.ts
  koco/src/hooks/custom/useInput.ts
  koco/src/hooks/mutations/useAuthMutations.ts
  koco/src/hooks/mutations/useProblemMutations.ts
  koco/src/hooks/mutations/useUserMutations.ts
  koco/src/hooks/queries/queryKeys.ts
  koco/src/hooks/queries/useProblemQueries.ts
  koco/src/hooks/queries/useUserQueries.ts
  koco/src/pages/FirstLoginPage/index.tsx
  koco/src/pages/KakaoCallbackPage/index.tsx
  koco/src/pages/Login/components/LoginCard/index.tsx
  koco/src/pages/MainPage/components/ProfileCard/index.tsx
  koco/src/pages/MainPage/components/TotalStudyCard/RadarChart/index.tsx
  koco/src/pages/MainPage/index.tsx
  koco/src/pages/ProblemListPage/components/Calendar/index.tsx
  koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx
  koco/src/pages/ProblemListPage/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/pages/ProblemSolutionPage/index.tsx
  koco/src/pages/SurveyPage/index.tsx
  koco/src/provider/QueryProvider/index.tsx
  koco/src/routes/RootRoutes.tsx
  koco/src/temp/mock/dashboard.json
  koco/src/temp/mock/dashboard.ts
  koco/src/temp/mock/dateProblem.json
  koco/src/temp/mock/dateProblem.ts
  koco/src/temp/mock/solution.json
  koco/src/temp/mock/solution.ts
  koco/vitest.workspace.ts
Labels: 🧹chore, FE

#22 [CHORE] API 연결 수정 (#21)
  koco/src/apis/authApi.ts
  koco/src/apis/axios/index.ts
  koco/src/apis/problemApi.ts
  koco/src/apis/userApi.ts
  koco/src/components/layout/BottomNav/index.tsx
  koco/src/hooks/mutations/useAuthMutations.ts
  koco/src/hooks/mutations/useProblemMutations.ts
  koco/src/hooks/mutations/useUserMutations.ts
  koco/src/hooks/queries/useProblemQueries.ts
  koco/src/pages/FirstLoginPage/index.tsx
  koco/src/pages/KakaoCallbackPage/index.tsx
  koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx
  koco/src/pages/ProblemListPage/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
  koco/src/pages/ProblemSolutionPage/index.tsx
  koco/src/pages/SurveyPage/index.tsx
  koco/src/provider/QueryProvider/index.tsx
  koco/src/temp/mock/dashboard.ts
Labels: 🧹chore, FE

#23 [CHORE] 메인페이지 - 사용자 대시보드 api 연결 (#21)
  koco/src/hooks/queries/useUserQueries.ts
  koco/src/pages/MainPage/index.tsx
Labels: 🧹chore, FE

#28 [DOCUMENTATION] 코드 포맷 수정, 메타 태그 추가 (#24)
  koco/.prettierrc
  koco/index.html
  koco/public/Logo.svg
  koco/src/App.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
Labels: 📚documentation, FE

#29 [FEATURE] 로그아웃 UI 구현 및 api 연결 (#25)
  koco/src/apis/authApi.ts
  koco/src/assets/logoutIc.svg
  koco/src/components/layout/BottomNav/index.tsx
  koco/src/hooks/mutations/useAuthMutations.ts
Labels: ✨feature, FE

#32 [FEATURE] 자동 로그인 기능 구현 (#30)
  koco/src/App.tsx
  koco/src/apis/axios/index.ts
  koco/src/components/ui/Spinner/index.tsx
  koco/src/context/AuthContext.tsx
  koco/src/hooks/mutations/useAuthMutations.ts
  koco/src/pages/KakaoCallbackPage/index.tsx
  koco/src/pages/Login/index.tsx
  koco/src/routes/ProtectedRoute/index.tsx
  koco/src/routes/RootRoutes.tsx
Labels: ✨feature, FE

#35 [CHORE] QA 모드 설정 (#34)
  koco/src/routes/RootRoutes.tsx
  koco/tsconfig.json
  koco/vite.config.ts
Labels: 🧹chore, FE

#37 [FIX] 로그아웃 후 별도의 로그인 과정 없이 로그인 되는 현상 수정 (#36)
  koco/src/pages/Login/components/LoginCard/index.tsx
Labels: 🐞bug

#39 [BUG] 문제 데이터가 없을 시에도 설문 제출이 가능한 현상 수정 (#38)
  koco/src/pages/SurveyPage/index.tsx
Labels: 🐞bug, FE

#46 [CHORE] 문제 해설 페이지 - 코드 영역 개행 문자 적용, 누락된 데이터 반영, UI 디자인 수정 (#40)
  koco/src/apis/axios/index.ts
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
  koco/src/pages/ProblemSolutionPage/index.tsx
Labels: 🧹chore, FE

#47 [CHORE] 문제 리스트 조회 페이지 - 티어 라벨링 관련 디자인 시스템 설정 및 적용(#26)
  koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx
  koco/src/pages/ProblemListPage/index.tsx
  koco/tailwind.config.ts
Labels: 🧹chore, FE

#48 [BUG] logo click event 제거 (#42)
  koco/src/components/layout/Header/index.tsx
Labels: 🐞bug, FE

#49 [FEATURE] 오늘의 설문 한 번만 수행할 수 있도록 수정 (#41, #45)
  koco/src/@types/problem/index.ts
  koco/src/pages/MainPage/components/ProfileCard/index.tsx
  koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx
  koco/src/pages/ProblemListPage/index.tsx
  koco/src/pages/SurveyPage/index.tsx
Labels: 🐞bug, ✨feature, FE

#51 [FEATURE] 백준 티어 랭킹 데이터 문자열로 매핑 (#50)
  koco/src/pages/ProblemListPage/components/ProblemItem/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/utils/converter/convertTier.ts
Labels: ✨feature, FE

#52 [FEATURE] 메인페이지 UI 수정 (#44)
  koco/src/assets/kocoImage.svg
  koco/src/components/layout/Header/index.tsx
  koco/src/components/ui/Card/index.tsx
  koco/src/pages/MainPage/components/ChunsikCard/index.tsx
  koco/src/pages/MainPage/components/GameBannerCard/index.tsx
  koco/src/pages/MainPage/components/ProfileCard/index.tsx
  koco/src/pages/MainPage/components/TotalStudyCard/index.tsx
  koco/src/pages/MainPage/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
  koco/src/styles/global.css
  koco/tailwind.config.ts
Labels: ✨feature, FE

#61 [CHORE] 설문 페이지 - 데이터가 비어 있을 경우 핸들링 (#58)
  koco/src/pages/SurveyPage/index.tsx
Labels: 🧹chore, FE

#65 [CHORE] 문제 리스트 조회 페이지 - 하단바 추가 및 불필요한 조건부 렌더링 제거 (#60)
  koco/src/pages/ProblemListPage/index.tsx
  koco/src/pages/SurveyPage/index.tsx
Labels: 🧹chore, FE

#64 [BUG] 문제 리스트 조회 페이지 - 날짜 선택 시 쿼리 파라미터 변동 및 refetch 하도록 로직 수정 (#57)
  koco/src/pages/ProblemListPage/index.tsx
  koco/src/pages/SurveyPage/index.tsx
Labels: 🐞bug, FE

#66 [CHORE] 오픈 그래프 설정 및 메타 태그 추가 (#62)
  koco/index.html
  koco/public/openGraphImage.svg
Labels: 🧹chore, FE

#68 [CHORE] 리프레쉬 토큰 갱신 로직 수정 (#53)
  koco/index.html
  koco/public/openGraphImage.png
  koco/src/apis/axios/index.ts
Labels: 🧹chore, FE

#72 [FEATURE] 메인 페이지 - 유저 프로필 조회, 알고리즘 스탯 조회 API 연결 (#69)
  koco/src/@types/user/index.ts
  koco/src/apis/axios/index.ts
  koco/src/apis/userApi.ts
  koco/src/hooks/queries/queryKeys.ts
  koco/src/hooks/queries/useUserQueries.ts
  koco/src/pages/MainPage/components/ProfileCard/index.tsx
  koco/src/pages/MainPage/index.tsx
  koco/src/pages/SurveyPage/index.tsx
Labels: ✨feature, FE

#73 [FEATURE] 문제 해설 페이지 - problemSolving 데이터 포맷 함수 구현 (#71)
  koco/src/pages/MainPage/index.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
Labels: ✨feature, FE

#74 [FEATURE] 문제 해설 페이지 - 백준 문제 바로가기 UI 구현 (#70)
  koco/src/apis/problemApi.ts
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
Labels: ✨feature, FE

#78 Feat/77 ga4
  koco/index.html
  koco/src/App.tsx
  koco/src/routes/RootRoutes.tsx
  koco/src/utils/GoogleAnalytics.tsx
Labels: ✨feature, FE

#83 [CHORE] 콘솔 제거 (#80)
  koco/src/apis/axios/index.ts
  koco/src/apis/problemApi.ts
  koco/src/apis/userApi.ts
  koco/src/hooks/mutations/useAuthMutations.ts
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
  koco/src/pages/SurveyPage/index.tsx
Labels: 🧹chore, FE

#85 [ENHANCEMENT] 라우팅 로직 변경 (#67)
  koco/src/apis/axios/index.ts
  koco/src/context/AuthContext.tsx
  koco/src/routes/ProtectedRoute/index.tsx
  koco/src/routes/RootRoutes.tsx
Labels: 🔧enhancement, FE

#87 [BUG] 문제 요약 부분 줄바꿈이 이상한 문제 (#86)
  koco/src/pages/ProblemSolutionPage/components/ProblemSolutionSection/index.tsx
Labels: 🐞bug, FE

#89 [FEATURE] 수식 데이터 전처리 로직 구현 (#81)
  koco/package-lock.json
  koco/package.json
  koco/src/main.tsx
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/styles/global.css
  koco/src/utils/converter/processMathText.ts
  koco/src/vite-env.d.ts
Labels: ✨feature, FE

#90 [FEATURE] 예시 입력, 예시 출력이 여러개일 경우 구분 출력 (#88)
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
Labels: 🐞bug, FE

#93 [ENHANCEMENT] 문제 영역 html 렌더링 및 수식 데이터 포맷 처리 함수 구현 (#91)
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/utils/converter/processMathHtml.ts
  koco/src/vite-env.d.ts
Labels: 🔧enhancement, FE

#112 [CHORE] MathJax 폰트 preload, resize 이벤트 적용, css 수정 (#111)
  koco/index.html
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/styles/global.css
  koco/src/utils/converter/processMathHtml.ts
Labels: 🧹chore, FE

#113 [CHORE] css 수정, 불필요한 폰트 preload제거 (#111)
  koco/index.html
  koco/src/styles/global.css
Labels: 🐞bug, 🧹chore, FE

#114 [CHORE] MathJax 라이브러리 렌더링 순서 제어 (#111)
  koco/src/pages/ProblemSolutionPage/components/ProblemDetailSection/index.tsx
  koco/src/styles/global.css
Labels: 🐞bug, 🧹chore, FE
